import type { DmcColour } from "../types/thread";

// Generated by scripts/generate-dmc-catalogue.mjs from DMC's US 117MC product data.
// Names and screen colours are approximate reference aids for personal use.
export const moulineSpecialColours = [
    {
        "dmcNumber": "01",
        "colourName": "Rain",
        "hex": "#D8D8D8"
    },
    {
        "dmcNumber": "02",
        "colourName": "Mist",
        "hex": "#D8D8D8"
    },
    {
        "dmcNumber": "03",
        "colourName": "Dust",
        "hex": "#B8B8B8"
    },
    {
        "dmcNumber": "04",
        "colourName": "Shadow",
        "hex": "#787878"
    },
    {
        "dmcNumber": "05",
        "colourName": "Frosted Glass",
        "hex": "#D8C8B8"
    },
    {
        "dmcNumber": "06",
        "colourName": "Koala",
        "hex": "#D8C8B8"
    },
    {
        "dmcNumber": "07",
        "colourName": "Rhino",
        "hex": "#A89888"
    },
    {
        "dmcNumber": "08",
        "colourName": "Racoon",
        "hex": "#785848"
    },
    {
        "dmcNumber": "09",
        "colourName": "Pine Marten",
        "hex": "#483838"
    },
    {
        "dmcNumber": "10",
        "colourName": "Lemon Sherbert",
        "hex": "#E8E8B8"
    },
    {
        "dmcNumber": "11",
        "colourName": "Lemon Drop",
        "hex": "#E8E888"
    },
    {
        "dmcNumber": "12",
        "colourName": "Citrus Yellow",
        "hex": "#D8D858"
    },
    {
        "dmcNumber": "13",
        "colourName": "Spearmint",
        "hex": "#B8D8A8"
    },
    {
        "dmcNumber": "14",
        "colourName": "Bok Choy",
        "hex": "#E8F8B8"
    },
    {
        "dmcNumber": "15",
        "colourName": "Spring Onion",
        "hex": "#D8E898"
    },
    {
        "dmcNumber": "16",
        "colourName": "Sprout",
        "hex": "#C8D868"
    },
    {
        "dmcNumber": "17",
        "colourName": "Maize",
        "hex": "#F8E878"
    },
    {
        "dmcNumber": "18",
        "colourName": "Corn",
        "hex": "#F8D858"
    },
    {
        "dmcNumber": "19",
        "colourName": "Soft Peach",
        "hex": "#F8D878"
    },
    {
        "dmcNumber": "20",
        "colourName": "Peach",
        "hex": "#F8D8B8"
    },
    {
        "dmcNumber": "21",
        "colourName": "Prosciutto",
        "hex": "#C87858"
    },
    {
        "dmcNumber": "22",
        "colourName": "Ruby",
        "hex": "#B84838"
    },
    {
        "dmcNumber": "23",
        "colourName": "Sakura",
        "hex": "#F8E8E8"
    },
    {
        "dmcNumber": "24",
        "colourName": "Heather White",
        "hex": "#E8D8E8"
    },
    {
        "dmcNumber": "25",
        "colourName": "Cornflower White",
        "hex": "#D8C8D8"
    },
    {
        "dmcNumber": "26",
        "colourName": "Lavender White",
        "hex": "#D8D8E8"
    },
    {
        "dmcNumber": "27",
        "colourName": "Ash White",
        "hex": "#E8E8E8"
    },
    {
        "dmcNumber": "28",
        "colourName": "Lavender Gray",
        "hex": "#887898"
    },
    {
        "dmcNumber": "29",
        "colourName": "Emperor Purple",
        "hex": "#382848"
    },
    {
        "dmcNumber": "30",
        "colourName": "Kitten Gray",
        "hex": "#9898B8"
    },
    {
        "dmcNumber": "31",
        "colourName": "Dusty Violet",
        "hex": "#585888"
    },
    {
        "dmcNumber": "32",
        "colourName": "Antique Mauve",
        "hex": "#484878"
    },
    {
        "dmcNumber": "33",
        "colourName": "Allium",
        "hex": "#A85898"
    },
    {
        "dmcNumber": "34",
        "colourName": "Tyrian",
        "hex": "#681848"
    },
    {
        "dmcNumber": "35",
        "colourName": "Plum",
        "hex": "#581838"
    },
    {
        "dmcNumber": "48",
        "colourName": "Indian Rose Ombre",
        "hex": "#E8A8B8"
    },
    {
        "dmcNumber": "51",
        "colourName": "Pumpkin Ombre",
        "hex": "#D85808"
    },
    {
        "dmcNumber": "52",
        "colourName": "Violet Perfume Ombre",
        "hex": "#684888"
    },
    {
        "dmcNumber": "53",
        "colourName": "Nocturnal Ombre",
        "hex": "#282828"
    },
    {
        "dmcNumber": "69",
        "colourName": "Mahogany Ombre",
        "hex": "#882818"
    },
    {
        "dmcNumber": "90",
        "colourName": "Sunny Yellow Ombre",
        "hex": "#E8B868"
    },
    {
        "dmcNumber": "92",
        "colourName": "Foliage Green Ombre",
        "hex": "#384808"
    },
    {
        "dmcNumber": "93",
        "colourName": "Cornflower Ombre",
        "hex": "#78A8C8"
    },
    {
        "dmcNumber": "94",
        "colourName": "Moss Green Ombre",
        "hex": "#989838"
    },
    {
        "dmcNumber": "99",
        "colourName": "Redouté Rose Ombre",
        "hex": "#A84858"
    },
    {
        "dmcNumber": "105",
        "colourName": "Woodwork Ombre",
        "hex": "#B88858"
    },
    {
        "dmcNumber": "106",
        "colourName": "Mercurochrome Ombre",
        "hex": "#E84828"
    },
    {
        "dmcNumber": "107",
        "colourName": "Passion Pink Ombre",
        "hex": "#C82838"
    },
    {
        "dmcNumber": "111",
        "colourName": "Burnt Savannah Ombre",
        "hex": "#985808"
    },
    {
        "dmcNumber": "115",
        "colourName": "Opera Red Ombre",
        "hex": "#681818"
    },
    {
        "dmcNumber": "121",
        "colourName": "Cyclades Blue Ombre",
        "hex": "#082868"
    },
    {
        "dmcNumber": "125",
        "colourName": "Spring Green Ombre",
        "hex": "#A8C898"
    },
    {
        "dmcNumber": "150",
        "colourName": "Dusty Rose - Ultra Very Dark",
        "hex": "#580828"
    },
    {
        "dmcNumber": "151",
        "colourName": "Dusty Rose - Very Light",
        "hex": "#D88898"
    },
    {
        "dmcNumber": "152",
        "colourName": "Shell Pink - Medium Light",
        "hex": "#B87878"
    },
    {
        "dmcNumber": "153",
        "colourName": "Violet - Very Light",
        "hex": "#B888A8"
    },
    {
        "dmcNumber": "154",
        "colourName": "Grape - Very Dark",
        "hex": "#180818"
    },
    {
        "dmcNumber": "155",
        "colourName": "Blue Violet - Medium Dark",
        "hex": "#7868A8"
    },
    {
        "dmcNumber": "156",
        "colourName": "Blue Violet - Medium Light",
        "hex": "#6878A8"
    },
    {
        "dmcNumber": "157",
        "colourName": "Cornflower Blue - Very Light",
        "hex": "#98A8C8"
    },
    {
        "dmcNumber": "158",
        "colourName": "Cornflower Blu - Medium Very Dark",
        "hex": "#283878"
    },
    {
        "dmcNumber": "159",
        "colourName": "Gray Blue - Light",
        "hex": "#A8A8C8"
    },
    {
        "dmcNumber": "160",
        "colourName": "Gray Blue - Medium",
        "hex": "#586888"
    },
    {
        "dmcNumber": "161",
        "colourName": "Gray Blue",
        "hex": "#484878"
    },
    {
        "dmcNumber": "162",
        "colourName": "Blue - Ultra Very Light",
        "hex": "#98B8C8"
    },
    {
        "dmcNumber": "163",
        "colourName": "Celadon Green - Medium",
        "hex": "#385848"
    },
    {
        "dmcNumber": "164",
        "colourName": "Forest Green - Light",
        "hex": "#A8C898"
    },
    {
        "dmcNumber": "165",
        "colourName": "Moss Green - Very Light",
        "hex": "#E8D878"
    },
    {
        "dmcNumber": "166",
        "colourName": "Moss Green - Medium Light",
        "hex": "#B8B838"
    },
    {
        "dmcNumber": "167",
        "colourName": "Yellow Beige - Very Dark",
        "hex": "#A87838"
    },
    {
        "dmcNumber": "168",
        "colourName": "Pewter - Very Light",
        "hex": "#788888"
    },
    {
        "dmcNumber": "169",
        "colourName": "Pewter - Light",
        "hex": "#788888"
    },
    {
        "dmcNumber": "208",
        "colourName": "Lavender - Very Dark",
        "hex": "#682888"
    },
    {
        "dmcNumber": "209",
        "colourName": "Lavender - Dark",
        "hex": "#C888E8"
    },
    {
        "dmcNumber": "210",
        "colourName": "Lavender - Medium",
        "hex": "#B888D8"
    },
    {
        "dmcNumber": "211",
        "colourName": "Lavender - Light",
        "hex": "#E8D8F8"
    },
    {
        "dmcNumber": "221",
        "colourName": "Shell Pink - Very Dark",
        "hex": "#582828"
    },
    {
        "dmcNumber": "223",
        "colourName": "Shell Pink - Light",
        "hex": "#984848"
    },
    {
        "dmcNumber": "224",
        "colourName": "Shell Pink - Very Light",
        "hex": "#F8D8D8"
    },
    {
        "dmcNumber": "225",
        "colourName": "Shell Pink - Ultra Very Light",
        "hex": "#D8B8B8"
    },
    {
        "dmcNumber": "300",
        "colourName": "Mahogany - Very Dark",
        "hex": "#482818"
    },
    {
        "dmcNumber": "301",
        "colourName": "Mahogany - Medium",
        "hex": "#B86828"
    },
    {
        "dmcNumber": "304",
        "colourName": "Red - Medium",
        "hex": "#881828"
    },
    {
        "dmcNumber": "307",
        "colourName": "Lemon",
        "hex": "#F8D818"
    },
    {
        "dmcNumber": "309",
        "colourName": "Rose - Dark",
        "hex": "#C82838"
    },
    {
        "dmcNumber": "310",
        "colourName": "Black",
        "hex": "#181818"
    },
    {
        "dmcNumber": "311",
        "colourName": "Navy Blue - Medium",
        "hex": "#083868"
    },
    {
        "dmcNumber": "312",
        "colourName": "Baby Blue - Very Dark",
        "hex": "#080808"
    },
    {
        "dmcNumber": "315",
        "colourName": "Antique Mauve - Medium Dark",
        "hex": "#582838"
    },
    {
        "dmcNumber": "316",
        "colourName": "Antique Mauve - Medium",
        "hex": "#985878"
    },
    {
        "dmcNumber": "317",
        "colourName": "Pewter Gray",
        "hex": "#383848"
    },
    {
        "dmcNumber": "318",
        "colourName": "Steel Gray - Light",
        "hex": "#787898"
    },
    {
        "dmcNumber": "319",
        "colourName": "Pistachio Green - Very Dark",
        "hex": "#283828"
    },
    {
        "dmcNumber": "320",
        "colourName": "Pistachio Green - Medium",
        "hex": "#688868"
    },
    {
        "dmcNumber": "321",
        "colourName": "Red",
        "hex": "#A81818"
    },
    {
        "dmcNumber": "322",
        "colourName": "Baby Blue - Dark",
        "hex": "#485888"
    },
    {
        "dmcNumber": "326",
        "colourName": "Rose - Very Dark",
        "hex": "#A81828"
    },
    {
        "dmcNumber": "327",
        "colourName": "Violet - Dark",
        "hex": "#582858"
    },
    {
        "dmcNumber": "333",
        "colourName": "Blue Violet - Very Dark",
        "hex": "#382868"
    },
    {
        "dmcNumber": "334",
        "colourName": "Baby Blue - Medium",
        "hex": "#6888B8"
    },
    {
        "dmcNumber": "335",
        "colourName": "Rose",
        "hex": "#984848"
    },
    {
        "dmcNumber": "336",
        "colourName": "Navy Blue",
        "hex": "#181828"
    },
    {
        "dmcNumber": "340",
        "colourName": "Blue Violet - Medium",
        "hex": "#6858A8"
    },
    {
        "dmcNumber": "341",
        "colourName": "Blue Violet - Light",
        "hex": "#B8C8E8"
    },
    {
        "dmcNumber": "347",
        "colourName": "Salmon - Very Dark",
        "hex": "#A82818"
    },
    {
        "dmcNumber": "349",
        "colourName": "Coral - Dark",
        "hex": "#D82828"
    },
    {
        "dmcNumber": "350",
        "colourName": "Coral - Medium",
        "hex": "#C82818"
    },
    {
        "dmcNumber": "351",
        "colourName": "Coral",
        "hex": "#C83828"
    },
    {
        "dmcNumber": "352",
        "colourName": "Coral - Light",
        "hex": "#F88878"
    },
    {
        "dmcNumber": "353",
        "colourName": "Peach",
        "hex": "#D89878"
    },
    {
        "dmcNumber": "355",
        "colourName": "Terra Cotta - Dark",
        "hex": "#681808"
    },
    {
        "dmcNumber": "356",
        "colourName": "Terra Cotta - Medium",
        "hex": "#883838"
    },
    {
        "dmcNumber": "367",
        "colourName": "Pistachio Green - Dark",
        "hex": "#486848"
    },
    {
        "dmcNumber": "368",
        "colourName": "Pistachio Green - Light",
        "hex": "#78A868"
    },
    {
        "dmcNumber": "369",
        "colourName": "Pistachio Green - Very Light",
        "hex": "#B8C8A8"
    },
    {
        "dmcNumber": "370",
        "colourName": "Mustard - Medium",
        "hex": "#787838"
    },
    {
        "dmcNumber": "371",
        "colourName": "Mustard",
        "hex": "#584828"
    },
    {
        "dmcNumber": "372",
        "colourName": "Mustard - Light",
        "hex": "#988858"
    },
    {
        "dmcNumber": "400",
        "colourName": "Mahogany - Dark",
        "hex": "#481808"
    },
    {
        "dmcNumber": "402",
        "colourName": "Mahogany - Very Light",
        "hex": "#D88848"
    },
    {
        "dmcNumber": "407",
        "colourName": "Desert Sand - Dark",
        "hex": "#A87858"
    },
    {
        "dmcNumber": "413",
        "colourName": "Pewter Gray - Dark",
        "hex": "#080808"
    },
    {
        "dmcNumber": "414",
        "colourName": "Steel Gray - Dark",
        "hex": "#484858"
    },
    {
        "dmcNumber": "415",
        "colourName": "Pearl Gray",
        "hex": "#9898A8"
    },
    {
        "dmcNumber": "420",
        "colourName": "Hazelnut Brown - Dark",
        "hex": "#A86828"
    },
    {
        "dmcNumber": "422",
        "colourName": "Hazelnut Brown - Light",
        "hex": "#E8B868"
    },
    {
        "dmcNumber": "433",
        "colourName": "Brown - Medium",
        "hex": "#381808"
    },
    {
        "dmcNumber": "434",
        "colourName": "Brown - Light",
        "hex": "#582808"
    },
    {
        "dmcNumber": "435",
        "colourName": "Brown - Very Light",
        "hex": "#785828"
    },
    {
        "dmcNumber": "436",
        "colourName": "Tan",
        "hex": "#985828"
    },
    {
        "dmcNumber": "437",
        "colourName": "Tan - Light",
        "hex": "#F8C898"
    },
    {
        "dmcNumber": "444",
        "colourName": "Lemon - Dark",
        "hex": "#F8D818"
    },
    {
        "dmcNumber": "445",
        "colourName": "Lemon - Light",
        "hex": "#E8E858"
    },
    {
        "dmcNumber": "451",
        "colourName": "Shell Gray - Dark",
        "hex": "#785858"
    },
    {
        "dmcNumber": "452",
        "colourName": "Shell Gray - Medium",
        "hex": "#887878"
    },
    {
        "dmcNumber": "453",
        "colourName": "Shell Gray - Light",
        "hex": "#B8A8A8"
    },
    {
        "dmcNumber": "469",
        "colourName": "Avocado Green",
        "hex": "#585828"
    },
    {
        "dmcNumber": "470",
        "colourName": "Avocado Green - Light",
        "hex": "#687828"
    },
    {
        "dmcNumber": "471",
        "colourName": "Avocado Green - Very Light",
        "hex": "#687828"
    },
    {
        "dmcNumber": "472",
        "colourName": "Avocado Green - Ultra Light",
        "hex": "#B8C858"
    },
    {
        "dmcNumber": "498",
        "colourName": "Red - Dark",
        "hex": "#B80848"
    },
    {
        "dmcNumber": "500",
        "colourName": "Blue Green - Very Dark",
        "hex": "#182828"
    },
    {
        "dmcNumber": "501",
        "colourName": "Blue Green - Dark",
        "hex": "#485858"
    },
    {
        "dmcNumber": "502",
        "colourName": "Blue Green",
        "hex": "#485848"
    },
    {
        "dmcNumber": "503",
        "colourName": "Blue Green - Medium",
        "hex": "#689888"
    },
    {
        "dmcNumber": "504",
        "colourName": "Blue Green - Very Light",
        "hex": "#98A898"
    },
    {
        "dmcNumber": "505",
        "colourName": "Jade Green",
        "hex": "#284838"
    },
    {
        "dmcNumber": "517",
        "colourName": "Wedgewood - Dark",
        "hex": "#183858"
    },
    {
        "dmcNumber": "518",
        "colourName": "Wedgewood - Light",
        "hex": "#4888A8"
    },
    {
        "dmcNumber": "519",
        "colourName": "Sky Blue",
        "hex": "#88B8C8"
    },
    {
        "dmcNumber": "520",
        "colourName": "Fern Green - Dark",
        "hex": "#283828"
    },
    {
        "dmcNumber": "522",
        "colourName": "Fern Green",
        "hex": "#788868"
    },
    {
        "dmcNumber": "523",
        "colourName": "Fern Green - Light",
        "hex": "#989878"
    },
    {
        "dmcNumber": "524",
        "colourName": "Fern Green - Very Light",
        "hex": "#989888"
    },
    {
        "dmcNumber": "535",
        "colourName": "Ash Gray - Very Light",
        "hex": "#585858"
    },
    {
        "dmcNumber": "543",
        "colourName": "Beige Brown - Ultra Very Light",
        "hex": "#D8C8B8"
    },
    {
        "dmcNumber": "550",
        "colourName": "Violet - Very Dark",
        "hex": "#381848"
    },
    {
        "dmcNumber": "552",
        "colourName": "Violet - Medium",
        "hex": "#8848A8"
    },
    {
        "dmcNumber": "553",
        "colourName": "Violet",
        "hex": "#785898"
    },
    {
        "dmcNumber": "554",
        "colourName": "Violet - Light",
        "hex": "#B888C8"
    },
    {
        "dmcNumber": "561",
        "colourName": "Jade - Very Dark",
        "hex": "#284838"
    },
    {
        "dmcNumber": "562",
        "colourName": "Jade - Medium",
        "hex": "#589868"
    },
    {
        "dmcNumber": "563",
        "colourName": "Jade - Light",
        "hex": "#78A888"
    },
    {
        "dmcNumber": "564",
        "colourName": "Jade - Very Light",
        "hex": "#98C8A8"
    },
    {
        "dmcNumber": "580",
        "colourName": "Moss Green - Dark",
        "hex": "#484808"
    },
    {
        "dmcNumber": "581",
        "colourName": "Moss Green",
        "hex": "#687818"
    },
    {
        "dmcNumber": "597",
        "colourName": "Turquoise",
        "hex": "#387888"
    },
    {
        "dmcNumber": "598",
        "colourName": "Turquoise - Light",
        "hex": "#7898A8"
    },
    {
        "dmcNumber": "600",
        "colourName": "Cranberry - Very Dark",
        "hex": "#980838"
    },
    {
        "dmcNumber": "601",
        "colourName": "Cranberry - Dark",
        "hex": "#A82848"
    },
    {
        "dmcNumber": "602",
        "colourName": "Cranberry - Medium",
        "hex": "#D84878"
    },
    {
        "dmcNumber": "603",
        "colourName": "Cranberry",
        "hex": "#D86898"
    },
    {
        "dmcNumber": "604",
        "colourName": "Cranberry - Light",
        "hex": "#E888A8"
    },
    {
        "dmcNumber": "605",
        "colourName": "Cranberry - Very Light",
        "hex": "#E8B8C8"
    },
    {
        "dmcNumber": "606",
        "colourName": "Orange Red - Bright",
        "hex": "#B80808"
    },
    {
        "dmcNumber": "608",
        "colourName": "Orange - Bright",
        "hex": "#C84818"
    },
    {
        "dmcNumber": "610",
        "colourName": "Drab Brown - Dark",
        "hex": "#584828"
    },
    {
        "dmcNumber": "611",
        "colourName": "Drab Brown",
        "hex": "#584828"
    },
    {
        "dmcNumber": "612",
        "colourName": "Drab Brown - Light",
        "hex": "#786848"
    },
    {
        "dmcNumber": "613",
        "colourName": "Drab Brown - Very Light",
        "hex": "#A89878"
    },
    {
        "dmcNumber": "632",
        "colourName": "Desert Sand - Ultra Very Dark",
        "hex": "#683838"
    },
    {
        "dmcNumber": "640",
        "colourName": "Beige Gray - Very Dark",
        "hex": "#787858"
    },
    {
        "dmcNumber": "642",
        "colourName": "Beige Gray - Dark",
        "hex": "#787858"
    },
    {
        "dmcNumber": "644",
        "colourName": "Beige Gray - Medium",
        "hex": "#B8B898"
    },
    {
        "dmcNumber": "645",
        "colourName": "Beaver Gray - Very Dark",
        "hex": "#382828"
    },
    {
        "dmcNumber": "646",
        "colourName": "Beaver Gray - Dark",
        "hex": "#585848"
    },
    {
        "dmcNumber": "647",
        "colourName": "Beaver Gray - Medium",
        "hex": "#888878"
    },
    {
        "dmcNumber": "648",
        "colourName": "Beaver Gray - Light",
        "hex": "#B8A8A8"
    },
    {
        "dmcNumber": "666",
        "colourName": "Red - Bright",
        "hex": "#A80808"
    },
    {
        "dmcNumber": "676",
        "colourName": "Old Gold - Light",
        "hex": "#E8B868"
    },
    {
        "dmcNumber": "677",
        "colourName": "Old Gold - Very Light",
        "hex": "#D8C888"
    },
    {
        "dmcNumber": "680",
        "colourName": "Old Gold - Dark",
        "hex": "#886818"
    },
    {
        "dmcNumber": "699",
        "colourName": "Green",
        "hex": "#084818"
    },
    {
        "dmcNumber": "700",
        "colourName": "Green - Bright",
        "hex": "#286838"
    },
    {
        "dmcNumber": "701",
        "colourName": "Green - Light",
        "hex": "#389848"
    },
    {
        "dmcNumber": "702",
        "colourName": "Kelly Green",
        "hex": "#58A848"
    },
    {
        "dmcNumber": "703",
        "colourName": "Chartreuse",
        "hex": "#88B858"
    },
    {
        "dmcNumber": "704",
        "colourName": "Chartreuse - Bright",
        "hex": "#98C858"
    },
    {
        "dmcNumber": "712",
        "colourName": "Cream",
        "hex": "#D8D8C8"
    },
    {
        "dmcNumber": "718",
        "colourName": "Plum",
        "hex": "#782858"
    },
    {
        "dmcNumber": "720",
        "colourName": "Orange Spice - Dark",
        "hex": "#C84818"
    },
    {
        "dmcNumber": "721",
        "colourName": "Orange Spice - Medium",
        "hex": "#C86838"
    },
    {
        "dmcNumber": "722",
        "colourName": "Orange Spice - Light",
        "hex": "#F88838"
    },
    {
        "dmcNumber": "725",
        "colourName": "Topaz - Medium Light",
        "hex": "#F8B828"
    },
    {
        "dmcNumber": "726",
        "colourName": "Topaz - Light",
        "hex": "#F8D848"
    },
    {
        "dmcNumber": "727",
        "colourName": "Topaz - Very Light",
        "hex": "#F8F8C8"
    },
    {
        "dmcNumber": "728",
        "colourName": "Topaz",
        "hex": "#C89828"
    },
    {
        "dmcNumber": "729",
        "colourName": "Old Gold - Medium",
        "hex": "#C89838"
    },
    {
        "dmcNumber": "730",
        "colourName": "Olive Green - Very Dark",
        "hex": "#584838"
    },
    {
        "dmcNumber": "731",
        "colourName": "Olive Green - Dark",
        "hex": "#787828"
    },
    {
        "dmcNumber": "732",
        "colourName": "Olive Green",
        "hex": "#383808"
    },
    {
        "dmcNumber": "733",
        "colourName": "Olive Green - Medium",
        "hex": "#786838"
    },
    {
        "dmcNumber": "734",
        "colourName": "Olive Green - Light",
        "hex": "#786838"
    },
    {
        "dmcNumber": "738",
        "colourName": "Tan - Very Light",
        "hex": "#B89868"
    },
    {
        "dmcNumber": "739",
        "colourName": "Tan - Ultra Very Light",
        "hex": "#D8C8A8"
    },
    {
        "dmcNumber": "740",
        "colourName": "Tangerine",
        "hex": "#F87818"
    },
    {
        "dmcNumber": "741",
        "colourName": "Tangerine - Medium",
        "hex": "#F89828"
    },
    {
        "dmcNumber": "742",
        "colourName": "Tangerine - Light",
        "hex": "#F8A818"
    },
    {
        "dmcNumber": "743",
        "colourName": "Yellow - Medium",
        "hex": "#F8C838"
    },
    {
        "dmcNumber": "744",
        "colourName": "Yellow - Pale",
        "hex": "#F8C848"
    },
    {
        "dmcNumber": "745",
        "colourName": "Yellow - Pale Light",
        "hex": "#E8D898"
    },
    {
        "dmcNumber": "746",
        "colourName": "Off White",
        "hex": "#D8D8C8"
    },
    {
        "dmcNumber": "747",
        "colourName": "Peacock Blue - Very Light",
        "hex": "#B8D8D8"
    },
    {
        "dmcNumber": "754",
        "colourName": "Peach - Light",
        "hex": "#D89878"
    },
    {
        "dmcNumber": "758",
        "colourName": "Terra Cotta - Very Light",
        "hex": "#D89878"
    },
    {
        "dmcNumber": "760",
        "colourName": "Salmon",
        "hex": "#B85858"
    },
    {
        "dmcNumber": "761",
        "colourName": "Salmon - Light",
        "hex": "#F8D8D8"
    },
    {
        "dmcNumber": "762",
        "colourName": "Pearl Gray - Very Light",
        "hex": "#D8D8D8"
    },
    {
        "dmcNumber": "772",
        "colourName": "Yellow Green - Very Light",
        "hex": "#C8D8A8"
    },
    {
        "dmcNumber": "775",
        "colourName": "Baby Blue - Very Light",
        "hex": "#B8C8D8"
    },
    {
        "dmcNumber": "777",
        "colourName": "Raspberry - Very Dark",
        "hex": "#680828"
    },
    {
        "dmcNumber": "778",
        "colourName": "Antique Mauve - Very Light",
        "hex": "#B89898"
    },
    {
        "dmcNumber": "779",
        "colourName": "Cocoa - Dark",
        "hex": "#180808"
    },
    {
        "dmcNumber": "780",
        "colourName": "Topaz - Ultra Very Dark",
        "hex": "#482808"
    },
    {
        "dmcNumber": "781",
        "colourName": "Topaz - Very Dark",
        "hex": "#C88838"
    },
    {
        "dmcNumber": "782",
        "colourName": "Topaz - Dark",
        "hex": "#784808"
    },
    {
        "dmcNumber": "783",
        "colourName": "Topaz - Medium",
        "hex": "#D89828"
    },
    {
        "dmcNumber": "791",
        "colourName": "Cornflower Blue - Very Dark",
        "hex": "#181848"
    },
    {
        "dmcNumber": "792",
        "colourName": "Cornflower Blue - Dark",
        "hex": "#282878"
    },
    {
        "dmcNumber": "793",
        "colourName": "Cornflower Blue - Medium",
        "hex": "#6878B8"
    },
    {
        "dmcNumber": "794",
        "colourName": "Cornflower Blue - Light",
        "hex": "#6888B8"
    },
    {
        "dmcNumber": "796",
        "colourName": "Royal Blue - Dark",
        "hex": "#181838"
    },
    {
        "dmcNumber": "797",
        "colourName": "Royal Blue",
        "hex": "#282858"
    },
    {
        "dmcNumber": "798",
        "colourName": "Delft Blue - Dark",
        "hex": "#384898"
    },
    {
        "dmcNumber": "799",
        "colourName": "Delft Blue - Medium",
        "hex": "#4878B8"
    },
    {
        "dmcNumber": "800",
        "colourName": "Delft Blue - Pale",
        "hex": "#A8C8D8"
    },
    {
        "dmcNumber": "801",
        "colourName": "Coffee Brown - Dark",
        "hex": "#482818"
    },
    {
        "dmcNumber": "803",
        "colourName": "Baby Blue - Ultra Very Dark",
        "hex": "#081838"
    },
    {
        "dmcNumber": "806",
        "colourName": "Peacock Blue - Dark",
        "hex": "#2888B8"
    },
    {
        "dmcNumber": "807",
        "colourName": "Peacock Blue",
        "hex": "#2898A8"
    },
    {
        "dmcNumber": "809",
        "colourName": "Delft Blue",
        "hex": "#4868A8"
    },
    {
        "dmcNumber": "813",
        "colourName": "Blue - Light",
        "hex": "#4888A8"
    },
    {
        "dmcNumber": "814",
        "colourName": "Garnet - Dark",
        "hex": "#280808"
    },
    {
        "dmcNumber": "815",
        "colourName": "Garnet - Medium",
        "hex": "#480818"
    },
    {
        "dmcNumber": "816",
        "colourName": "Garnet",
        "hex": "#380818"
    },
    {
        "dmcNumber": "817",
        "colourName": "Coral Red - Very Dark",
        "hex": "#680808"
    },
    {
        "dmcNumber": "818",
        "colourName": "Baby Pink",
        "hex": "#E8C8C8"
    },
    {
        "dmcNumber": "819",
        "colourName": "Baby Pink - Light",
        "hex": "#E8D8D8"
    },
    {
        "dmcNumber": "820",
        "colourName": "Royal Blue - Very Dark",
        "hex": "#080828"
    },
    {
        "dmcNumber": "822",
        "colourName": "Beige Gray - Light",
        "hex": "#D8D8C8"
    },
    {
        "dmcNumber": "823",
        "colourName": "Navy Blue - Dark",
        "hex": "#080818"
    },
    {
        "dmcNumber": "824",
        "colourName": "Blue - Very Dark",
        "hex": "#182858"
    },
    {
        "dmcNumber": "825",
        "colourName": "Blue - Dark",
        "hex": "#284878"
    },
    {
        "dmcNumber": "826",
        "colourName": "Blue - Medium",
        "hex": "#385888"
    },
    {
        "dmcNumber": "827",
        "colourName": "Blue - Very Light",
        "hex": "#78A8B8"
    },
    {
        "dmcNumber": "828",
        "colourName": "Sky Blue - Very Light",
        "hex": "#A8C8C8"
    },
    {
        "dmcNumber": "829",
        "colourName": "Golden Olive - Very Dark",
        "hex": "#382808"
    },
    {
        "dmcNumber": "830",
        "colourName": "Golden Olive - Dark",
        "hex": "#584838"
    },
    {
        "dmcNumber": "831",
        "colourName": "Golden Olive - Medium",
        "hex": "#483808"
    },
    {
        "dmcNumber": "832",
        "colourName": "Golden Olive",
        "hex": "#685808"
    },
    {
        "dmcNumber": "833",
        "colourName": "Golden Olive - Light",
        "hex": "#584808"
    },
    {
        "dmcNumber": "834",
        "colourName": "Golden Olive - Very Light",
        "hex": "#B89848"
    },
    {
        "dmcNumber": "838",
        "colourName": "Beige Brown - Very Dark",
        "hex": "#281818"
    },
    {
        "dmcNumber": "839",
        "colourName": "Beige Brown - Dark",
        "hex": "#281818"
    },
    {
        "dmcNumber": "840",
        "colourName": "Beige Brown - Medium",
        "hex": "#483828"
    },
    {
        "dmcNumber": "841",
        "colourName": "Beige Brown - Light",
        "hex": "#987868"
    },
    {
        "dmcNumber": "842",
        "colourName": "Beige Brown - Very Light",
        "hex": "#A89878"
    },
    {
        "dmcNumber": "844",
        "colourName": "Beaver Gray - Ultra Dark",
        "hex": "#181818"
    },
    {
        "dmcNumber": "869",
        "colourName": "Hazelnut Brown - Very Dark",
        "hex": "#584838"
    },
    {
        "dmcNumber": "890",
        "colourName": "Pistachio Green - Ultra Dark",
        "hex": "#182818"
    },
    {
        "dmcNumber": "891",
        "colourName": "Carnation - Dark",
        "hex": "#C80838"
    },
    {
        "dmcNumber": "892",
        "colourName": "Carnation - Medium",
        "hex": "#C80838"
    },
    {
        "dmcNumber": "893",
        "colourName": "Carnation - Light",
        "hex": "#B80838"
    },
    {
        "dmcNumber": "894",
        "colourName": "Carnation - Very Light",
        "hex": "#F8A8A8"
    },
    {
        "dmcNumber": "895",
        "colourName": "Hunter Green - Very Dark",
        "hex": "#182818"
    },
    {
        "dmcNumber": "898",
        "colourName": "Coffee Brown - Very Dark",
        "hex": "#180808"
    },
    {
        "dmcNumber": "899",
        "colourName": "Rose - Medium",
        "hex": "#D87888"
    },
    {
        "dmcNumber": "900",
        "colourName": "Burnt Orange - Dark",
        "hex": "#B82818"
    },
    {
        "dmcNumber": "902",
        "colourName": "Garnet - Very Dark",
        "hex": "#481828"
    },
    {
        "dmcNumber": "904",
        "colourName": "Parrot Green - Very Dark",
        "hex": "#383828"
    },
    {
        "dmcNumber": "905",
        "colourName": "Parrot Green - Dark",
        "hex": "#385818"
    },
    {
        "dmcNumber": "906",
        "colourName": "Parrot Green - Medium",
        "hex": "#587818"
    },
    {
        "dmcNumber": "907",
        "colourName": "Parrot Green - Light",
        "hex": "#98B828"
    },
    {
        "dmcNumber": "909",
        "colourName": "Emerald Green - Very Dark",
        "hex": "#082808"
    },
    {
        "dmcNumber": "910",
        "colourName": "Emerald Green - Dark",
        "hex": "#184828"
    },
    {
        "dmcNumber": "911",
        "colourName": "Emerald Green - Medium",
        "hex": "#185838"
    },
    {
        "dmcNumber": "912",
        "colourName": "Emerald Green - Light",
        "hex": "#287858"
    },
    {
        "dmcNumber": "913",
        "colourName": "Nile Green - Medium",
        "hex": "#48A868"
    },
    {
        "dmcNumber": "915",
        "colourName": "Plum - Dark",
        "hex": "#480828"
    },
    {
        "dmcNumber": "917",
        "colourName": "Plum - Medium",
        "hex": "#681848"
    },
    {
        "dmcNumber": "918",
        "colourName": "Red Copper - Dark",
        "hex": "#581818"
    },
    {
        "dmcNumber": "919",
        "colourName": "Red Copper",
        "hex": "#882828"
    },
    {
        "dmcNumber": "920",
        "colourName": "Copper - Medium",
        "hex": "#782828"
    },
    {
        "dmcNumber": "921",
        "colourName": "Copper",
        "hex": "#983828"
    },
    {
        "dmcNumber": "922",
        "colourName": "Copper - Light",
        "hex": "#C85828"
    },
    {
        "dmcNumber": "924",
        "colourName": "Gray Green - Very Dark",
        "hex": "#182838"
    },
    {
        "dmcNumber": "926",
        "colourName": "Gray Green - Medium",
        "hex": "#687878"
    },
    {
        "dmcNumber": "927",
        "colourName": "Gray Green - Light",
        "hex": "#788888"
    },
    {
        "dmcNumber": "928",
        "colourName": "Gray Green - Very Light",
        "hex": "#D8D8D8"
    },
    {
        "dmcNumber": "930",
        "colourName": "Antique Blue - Dark",
        "hex": "#182838"
    },
    {
        "dmcNumber": "931",
        "colourName": "Antique Blue - Medium",
        "hex": "#384868"
    },
    {
        "dmcNumber": "932",
        "colourName": "Antique Blue - Light",
        "hex": "#B8C8D8"
    },
    {
        "dmcNumber": "934",
        "colourName": "Avocado Green - Black",
        "hex": "#080808"
    },
    {
        "dmcNumber": "935",
        "colourName": "Avocado Green - Dark",
        "hex": "#281818"
    },
    {
        "dmcNumber": "936",
        "colourName": "Avocado Green - Very Dark",
        "hex": "#484828"
    },
    {
        "dmcNumber": "937",
        "colourName": "Avocado Green - Medium",
        "hex": "#283818"
    },
    {
        "dmcNumber": "938",
        "colourName": "Coffee Brown - Ultra Dark",
        "hex": "#180808"
    },
    {
        "dmcNumber": "939",
        "colourName": "Navy Blue - Very Dark",
        "hex": "#080818"
    },
    {
        "dmcNumber": "943",
        "colourName": "Aquamarine - Medium",
        "hex": "#289878"
    },
    {
        "dmcNumber": "945",
        "colourName": "Tawny",
        "hex": "#E8D8C8"
    },
    {
        "dmcNumber": "946",
        "colourName": "Burnt Orange - Medium",
        "hex": "#E85828"
    },
    {
        "dmcNumber": "947",
        "colourName": "Burnt Orange",
        "hex": "#E84808"
    },
    {
        "dmcNumber": "948",
        "colourName": "Peach - Very Light",
        "hex": "#E8C8B8"
    },
    {
        "dmcNumber": "950",
        "colourName": "Desert Sand - Light",
        "hex": "#D8B8A8"
    },
    {
        "dmcNumber": "951",
        "colourName": "Tawny - Light",
        "hex": "#E8C8A8"
    },
    {
        "dmcNumber": "954",
        "colourName": "Nile Green",
        "hex": "#58B868"
    },
    {
        "dmcNumber": "955",
        "colourName": "Nile Green - Light",
        "hex": "#88B878"
    },
    {
        "dmcNumber": "956",
        "colourName": "Geranium",
        "hex": "#D83858"
    },
    {
        "dmcNumber": "957",
        "colourName": "Geranium - Pale",
        "hex": "#E898A8"
    },
    {
        "dmcNumber": "958",
        "colourName": "Seagreen - Dark",
        "hex": "#489888"
    },
    {
        "dmcNumber": "959",
        "colourName": "Seagreen - Medium",
        "hex": "#086858"
    },
    {
        "dmcNumber": "961",
        "colourName": "Dusty Rose - Dark",
        "hex": "#C85878"
    },
    {
        "dmcNumber": "962",
        "colourName": "Dusty Rose - Medium",
        "hex": "#D898A8"
    },
    {
        "dmcNumber": "963",
        "colourName": "Dusty Rose - Ultra Very Light",
        "hex": "#E8B8B8"
    },
    {
        "dmcNumber": "964",
        "colourName": "Seagreen - Light",
        "hex": "#E8F8F8"
    },
    {
        "dmcNumber": "966",
        "colourName": "Baby Green - Medium",
        "hex": "#E8F8E8"
    },
    {
        "dmcNumber": "967",
        "colourName": "Apricot - Very Light",
        "hex": "#E8B8A8"
    },
    {
        "dmcNumber": "970",
        "colourName": "Pumpkin - Light",
        "hex": "#E84808"
    },
    {
        "dmcNumber": "971",
        "colourName": "Pumpkin",
        "hex": "#E87828"
    },
    {
        "dmcNumber": "972",
        "colourName": "Canary - Deep",
        "hex": "#E89808"
    },
    {
        "dmcNumber": "973",
        "colourName": "Canary - Bright",
        "hex": "#E8B808"
    },
    {
        "dmcNumber": "975",
        "colourName": "Golden Brown - Dark",
        "hex": "#381808"
    },
    {
        "dmcNumber": "976",
        "colourName": "Golden Brown - Medium",
        "hex": "#B86838"
    },
    {
        "dmcNumber": "977",
        "colourName": "Golden Brown - Light",
        "hex": "#A85818"
    },
    {
        "dmcNumber": "986",
        "colourName": "Forest Green - Very Dark",
        "hex": "#081808"
    },
    {
        "dmcNumber": "987",
        "colourName": "Forest Green - Dark",
        "hex": "#384828"
    },
    {
        "dmcNumber": "988",
        "colourName": "Forest Green - Medium",
        "hex": "#688848"
    },
    {
        "dmcNumber": "989",
        "colourName": "Forest Green",
        "hex": "#789858"
    },
    {
        "dmcNumber": "991",
        "colourName": "Aquamarine - Dark",
        "hex": "#084838"
    },
    {
        "dmcNumber": "992",
        "colourName": "Aquamarine - Light",
        "hex": "#68B8A8"
    },
    {
        "dmcNumber": "993",
        "colourName": "Aquamarine - Very Light",
        "hex": "#387868"
    },
    {
        "dmcNumber": "995",
        "colourName": "Electric Blue - Dark",
        "hex": "#084888"
    },
    {
        "dmcNumber": "996",
        "colourName": "Electric Blue - Medium",
        "hex": "#0878C8"
    },
    {
        "dmcNumber": "3011",
        "colourName": "Khaki Green - Dark",
        "hex": "#484828"
    },
    {
        "dmcNumber": "3012",
        "colourName": "Khaki Green - Medium",
        "hex": "#686838"
    },
    {
        "dmcNumber": "3013",
        "colourName": "Khaki Green - Light",
        "hex": "#989868"
    },
    {
        "dmcNumber": "3021",
        "colourName": "Brown Gray - Very Dark",
        "hex": "#080808"
    },
    {
        "dmcNumber": "3022",
        "colourName": "Brown Gray - Medium",
        "hex": "#686858"
    },
    {
        "dmcNumber": "3023",
        "colourName": "Brown Gray - Light",
        "hex": "#B8B8A8"
    },
    {
        "dmcNumber": "3024",
        "colourName": "Brown Gray - Very Light",
        "hex": "#C8C8C8"
    },
    {
        "dmcNumber": "3031",
        "colourName": "Mocha Brown - Very Dark",
        "hex": "#483828"
    },
    {
        "dmcNumber": "3032",
        "colourName": "Mocha Brown - Medium",
        "hex": "#585838"
    },
    {
        "dmcNumber": "3033",
        "colourName": "Mocha Brown - Very Light",
        "hex": "#F8F8F8"
    },
    {
        "dmcNumber": "3041",
        "colourName": "Antique Violet - Medium",
        "hex": "#483848"
    },
    {
        "dmcNumber": "3042",
        "colourName": "Antique Violet - Light",
        "hex": "#C8B8C8"
    },
    {
        "dmcNumber": "3045",
        "colourName": "Yellow Beige - Dark",
        "hex": "#987838"
    },
    {
        "dmcNumber": "3046",
        "colourName": "Yellow Beige - Medium",
        "hex": "#C8B878"
    },
    {
        "dmcNumber": "3047",
        "colourName": "Yellow Beige - Light",
        "hex": "#B8B888"
    },
    {
        "dmcNumber": "3051",
        "colourName": "Green Gray - Dark",
        "hex": "#282818"
    },
    {
        "dmcNumber": "3052",
        "colourName": "Green Gray - Medium",
        "hex": "#383828"
    },
    {
        "dmcNumber": "3053",
        "colourName": "Green Gray",
        "hex": "#B8B898"
    },
    {
        "dmcNumber": "3064",
        "colourName": "Desert Sand",
        "hex": "#885848"
    },
    {
        "dmcNumber": "3072",
        "colourName": "Beaver Gray - Very Light",
        "hex": "#D8D8D8"
    },
    {
        "dmcNumber": "3078",
        "colourName": "Golden Yellow - Very Light",
        "hex": "#E8E8B8"
    },
    {
        "dmcNumber": "3325",
        "colourName": "Baby Blue - Light",
        "hex": "#A8C8D8"
    },
    {
        "dmcNumber": "3326",
        "colourName": "Rose - Light",
        "hex": "#E8C8C8"
    },
    {
        "dmcNumber": "3328",
        "colourName": "Salmon - Dark",
        "hex": "#782828"
    },
    {
        "dmcNumber": "3340",
        "colourName": "Apricot - Medium",
        "hex": "#F88868"
    },
    {
        "dmcNumber": "3341",
        "colourName": "Apricot",
        "hex": "#E88878"
    },
    {
        "dmcNumber": "3345",
        "colourName": "Hunter Green - Dark",
        "hex": "#182818"
    },
    {
        "dmcNumber": "3346",
        "colourName": "Hunter Green",
        "hex": "#283818"
    },
    {
        "dmcNumber": "3347",
        "colourName": "Yellow Green - Medium",
        "hex": "#485828"
    },
    {
        "dmcNumber": "3348",
        "colourName": "Yellow Green - Light",
        "hex": "#989848"
    },
    {
        "dmcNumber": "3350",
        "colourName": "Dusty Rose - Ultra Dark",
        "hex": "#580828"
    },
    {
        "dmcNumber": "3354",
        "colourName": "Dusty Rose - Light",
        "hex": "#C88898"
    },
    {
        "dmcNumber": "3362",
        "colourName": "Pine Green - Dark",
        "hex": "#080808"
    },
    {
        "dmcNumber": "3363",
        "colourName": "Pine Green - Medium",
        "hex": "#586848"
    },
    {
        "dmcNumber": "3364",
        "colourName": "Pine Green",
        "hex": "#586838"
    },
    {
        "dmcNumber": "3371",
        "colourName": "Black Brown",
        "hex": "#080808"
    },
    {
        "dmcNumber": "3607",
        "colourName": "Plum - Light",
        "hex": "#782858"
    },
    {
        "dmcNumber": "3608",
        "colourName": "Plum - Very Light",
        "hex": "#A85878"
    },
    {
        "dmcNumber": "3609",
        "colourName": "Plum - Ultra Light",
        "hex": "#F8E8F8"
    },
    {
        "dmcNumber": "3685",
        "colourName": "Mauve - Very Dark",
        "hex": "#881531"
    },
    {
        "dmcNumber": "3687",
        "colourName": "Mauve",
        "hex": "#783848"
    },
    {
        "dmcNumber": "3688",
        "colourName": "Mauve - Medium",
        "hex": "#D8A8B8"
    },
    {
        "dmcNumber": "3689",
        "colourName": "Mauve - Light",
        "hex": "#D8B8C8"
    },
    {
        "dmcNumber": "3705",
        "colourName": "Melon - Dark",
        "hex": "#980828"
    },
    {
        "dmcNumber": "3706",
        "colourName": "Melon - Medium",
        "hex": "#E86878"
    },
    {
        "dmcNumber": "3708",
        "colourName": "Melon - Light",
        "hex": "#E8C8C8"
    },
    {
        "dmcNumber": "3712",
        "colourName": "Salmon - Medium",
        "hex": "#C84858"
    },
    {
        "dmcNumber": "3713",
        "colourName": "Salmon - Very Light",
        "hex": "#D8B8B8"
    },
    {
        "dmcNumber": "3716",
        "colourName": "Dusty Rose - Medium Very Light",
        "hex": "#F8F8F8"
    },
    {
        "dmcNumber": "3721",
        "colourName": "Shell Pink - Dark",
        "hex": "#782838"
    },
    {
        "dmcNumber": "3722",
        "colourName": "Shell Pink - Medium",
        "hex": "#783838"
    },
    {
        "dmcNumber": "3726",
        "colourName": "Antique Mauve - Dark",
        "hex": "#582838"
    },
    {
        "dmcNumber": "3727",
        "colourName": "Antique Mauve - Light",
        "hex": "#B88898"
    },
    {
        "dmcNumber": "3731",
        "colourName": "Dusty Rose - Very Dark",
        "hex": "#A82848"
    },
    {
        "dmcNumber": "3733",
        "colourName": "Dusty Rose",
        "hex": "#B85868"
    },
    {
        "dmcNumber": "3740",
        "colourName": "Antique Violet - Dark",
        "hex": "#482838"
    },
    {
        "dmcNumber": "3743",
        "colourName": "Antique Violet - Very Light",
        "hex": "#B8A8B8"
    },
    {
        "dmcNumber": "3746",
        "colourName": "Blue Violet - Dark",
        "hex": "#383878"
    },
    {
        "dmcNumber": "3747",
        "colourName": "Blue Violet - Very Light",
        "hex": "#A8B8C8"
    },
    {
        "dmcNumber": "3750",
        "colourName": "Antique Blue - Very Dark",
        "hex": "#182838"
    },
    {
        "dmcNumber": "3752",
        "colourName": "Antique Blue - Very Light",
        "hex": "#98A8B8"
    },
    {
        "dmcNumber": "3753",
        "colourName": "Antique Blue - Ultra Very Light",
        "hex": "#F8F8F8"
    },
    {
        "dmcNumber": "3755",
        "colourName": "Baby Blue",
        "hex": "#587898"
    },
    {
        "dmcNumber": "3756",
        "colourName": "Baby Blue - Ultra Very Light",
        "hex": "#A8B8B8"
    },
    {
        "dmcNumber": "3760",
        "colourName": "Wedgewood - Medium",
        "hex": "#083848"
    },
    {
        "dmcNumber": "3761",
        "colourName": "Sky Blue - Light",
        "hex": "#98B8C8"
    },
    {
        "dmcNumber": "3765",
        "colourName": "Peacock Blue - Very Dark",
        "hex": "#083848"
    },
    {
        "dmcNumber": "3766",
        "colourName": "Peacock Blue - Light",
        "hex": "#98C8C8"
    },
    {
        "dmcNumber": "3768",
        "colourName": "Gray Green - Dark",
        "hex": "#384858"
    },
    {
        "dmcNumber": "3770",
        "colourName": "Tawny - Very Light",
        "hex": "#E8D8D8"
    },
    {
        "dmcNumber": "3771",
        "colourName": "Terra Cotta - Ultra Very Light",
        "hex": "#E8C8B8"
    },
    {
        "dmcNumber": "3772",
        "colourName": "Desert Sand - Very Dark",
        "hex": "#784838"
    },
    {
        "dmcNumber": "3773",
        "colourName": "Desert Sand - Medium",
        "hex": "#A87868"
    },
    {
        "dmcNumber": "3774",
        "colourName": "Desert Sand - Very Light",
        "hex": "#D8B8A8"
    },
    {
        "dmcNumber": "3776",
        "colourName": "Mahogany - Light",
        "hex": "#C87848"
    },
    {
        "dmcNumber": "3777",
        "colourName": "Terra Cotta - Very Dark",
        "hex": "#580818"
    },
    {
        "dmcNumber": "3778",
        "colourName": "Terra Cotta - Light",
        "hex": "#B87868"
    },
    {
        "dmcNumber": "3779",
        "colourName": "Rosewood - Ultra Very Light",
        "hex": "#D8B8A8"
    },
    {
        "dmcNumber": "3781",
        "colourName": "Mocha Brown - Dark",
        "hex": "#483828"
    },
    {
        "dmcNumber": "3782",
        "colourName": "Mocha Brown - Light",
        "hex": "#B8B898"
    },
    {
        "dmcNumber": "3787",
        "colourName": "Brown Gray - Dark",
        "hex": "#383828"
    },
    {
        "dmcNumber": "3790",
        "colourName": "Beige Gray - Ultra Dark",
        "hex": "#584838"
    },
    {
        "dmcNumber": "3799",
        "colourName": "Pewter Gray - Very Dark",
        "hex": "#181818"
    },
    {
        "dmcNumber": "3801",
        "colourName": "Melon - Very Dark",
        "hex": "#C80838"
    },
    {
        "dmcNumber": "3802",
        "colourName": "Antique Mauve - Very Dark",
        "hex": "#381828"
    },
    {
        "dmcNumber": "3803",
        "colourName": "Mauve - Dark",
        "hex": "#480828"
    },
    {
        "dmcNumber": "3804",
        "colourName": "Cyclamen Pink - Dark",
        "hex": "#A80858"
    },
    {
        "dmcNumber": "3805",
        "colourName": "Cyclamen Pink",
        "hex": "#880848"
    },
    {
        "dmcNumber": "3806",
        "colourName": "Cyclamen Pink - Light",
        "hex": "#B85878"
    },
    {
        "dmcNumber": "3807",
        "colourName": "Cornflower Blue",
        "hex": "#485888"
    },
    {
        "dmcNumber": "3808",
        "colourName": "Turquoise - Ultra Very Dark",
        "hex": "#082828"
    },
    {
        "dmcNumber": "3809",
        "colourName": "Turquoise - Very Dark",
        "hex": "#083838"
    },
    {
        "dmcNumber": "3810",
        "colourName": "Turquoise - Dark",
        "hex": "#084858"
    },
    {
        "dmcNumber": "3811",
        "colourName": "Turquoise - Very Light",
        "hex": "#C8D8D8"
    },
    {
        "dmcNumber": "3812",
        "colourName": "Seagreen - Very Dark",
        "hex": "#087868"
    },
    {
        "dmcNumber": "3813",
        "colourName": "Blue Green - Light",
        "hex": "#A8B8A8"
    },
    {
        "dmcNumber": "3814",
        "colourName": "Aquamarine",
        "hex": "#084838"
    },
    {
        "dmcNumber": "3815",
        "colourName": "Celadon Green - Dark",
        "hex": "#284838"
    },
    {
        "dmcNumber": "3816",
        "colourName": "Celadon Green",
        "hex": "#689888"
    },
    {
        "dmcNumber": "3817",
        "colourName": "Celadon Green - Light",
        "hex": "#A8B8A8"
    },
    {
        "dmcNumber": "3818",
        "colourName": "Emerald Green - Ultra Very Dark",
        "hex": "#182818"
    },
    {
        "dmcNumber": "3819",
        "colourName": "Moss Green - Light",
        "hex": "#D8D888"
    },
    {
        "dmcNumber": "3820",
        "colourName": "Straw - Dark",
        "hex": "#D8B848"
    },
    {
        "dmcNumber": "3821",
        "colourName": "Straw",
        "hex": "#E8C868"
    },
    {
        "dmcNumber": "3822",
        "colourName": "Straw - Light",
        "hex": "#E8C878"
    },
    {
        "dmcNumber": "3823",
        "colourName": "Yellow - Ultra Pale",
        "hex": "#D8C8A8"
    },
    {
        "dmcNumber": "3824",
        "colourName": "Apricot - Light",
        "hex": "#E8B8A8"
    },
    {
        "dmcNumber": "3825",
        "colourName": "Pumpkin - Pale",
        "hex": "#D88858"
    },
    {
        "dmcNumber": "3826",
        "colourName": "Golden Brown",
        "hex": "#683818"
    },
    {
        "dmcNumber": "3827",
        "colourName": "Golden Brown - Pale",
        "hex": "#D8A868"
    },
    {
        "dmcNumber": "3828",
        "colourName": "Hazelnut Brown",
        "hex": "#886838"
    },
    {
        "dmcNumber": "3829",
        "colourName": "Old Gold - Very Dark",
        "hex": "#684808"
    },
    {
        "dmcNumber": "3830",
        "colourName": "Terra Cotta",
        "hex": "#783828"
    },
    {
        "dmcNumber": "3831",
        "colourName": "Raspberry - Dark",
        "hex": "#680828"
    },
    {
        "dmcNumber": "3832",
        "colourName": "Raspberry - Medium",
        "hex": "#A80838"
    },
    {
        "dmcNumber": "3833",
        "colourName": "Raspberry - Light",
        "hex": "#D86878"
    },
    {
        "dmcNumber": "3834",
        "colourName": "Grape - Dark",
        "hex": "#582848"
    },
    {
        "dmcNumber": "3835",
        "colourName": "Grape - Medium",
        "hex": "#784868"
    },
    {
        "dmcNumber": "3836",
        "colourName": "Grape - Light",
        "hex": "#986888"
    },
    {
        "dmcNumber": "3837",
        "colourName": "Lavender - Ultra Dark",
        "hex": "#381848"
    },
    {
        "dmcNumber": "3838",
        "colourName": "Lavender Blue - Dark",
        "hex": "#385898"
    },
    {
        "dmcNumber": "3839",
        "colourName": "Lavender Blue - Medium",
        "hex": "#98A8D8"
    },
    {
        "dmcNumber": "3840",
        "colourName": "Lavender Blue - Light",
        "hex": "#A8B8D8"
    },
    {
        "dmcNumber": "3841",
        "colourName": "Baby Blue - Pale",
        "hex": "#A8B8C8"
    },
    {
        "dmcNumber": "3842",
        "colourName": "Wedgewood - Very Dark",
        "hex": "#082838"
    },
    {
        "dmcNumber": "3843",
        "colourName": "Electric Blue",
        "hex": "#0888B8"
    },
    {
        "dmcNumber": "3844",
        "colourName": "Turquoise - Dark Bright",
        "hex": "#086868"
    },
    {
        "dmcNumber": "3845",
        "colourName": "Turquoise - Medium Bright",
        "hex": "#18A8B8"
    },
    {
        "dmcNumber": "3846",
        "colourName": "Turquoise - Light Bright",
        "hex": "#28A8B8"
    },
    {
        "dmcNumber": "3847",
        "colourName": "Teal Green - Dark",
        "hex": "#083838"
    },
    {
        "dmcNumber": "3848",
        "colourName": "Teal Green - Medium",
        "hex": "#084838"
    },
    {
        "dmcNumber": "3849",
        "colourName": "Teal Green - Light",
        "hex": "#78B8A8"
    },
    {
        "dmcNumber": "3850",
        "colourName": "Green Bright - Dark",
        "hex": "#085838"
    },
    {
        "dmcNumber": "3851",
        "colourName": "Green Bright - Light",
        "hex": "#48A888"
    },
    {
        "dmcNumber": "3852",
        "colourName": "Straw - Very Dark",
        "hex": "#B88808"
    },
    {
        "dmcNumber": "3853",
        "colourName": "Autumn Gold - Dark",
        "hex": "#E88848"
    },
    {
        "dmcNumber": "3854",
        "colourName": "Autumn Gold - Medium",
        "hex": "#E8A868"
    },
    {
        "dmcNumber": "3855",
        "colourName": "Autumn Gold - Light",
        "hex": "#F8D8A8"
    },
    {
        "dmcNumber": "3856",
        "colourName": "Mahogany - Ultra Very Light",
        "hex": "#C89868"
    },
    {
        "dmcNumber": "3857",
        "colourName": "Rosewood - Dark",
        "hex": "#482828"
    },
    {
        "dmcNumber": "3858",
        "colourName": "Rosewood - Medium",
        "hex": "#582828"
    },
    {
        "dmcNumber": "3859",
        "colourName": "Rosewood - Light",
        "hex": "#C89888"
    },
    {
        "dmcNumber": "3860",
        "colourName": "Cocoa",
        "hex": "#583838"
    },
    {
        "dmcNumber": "3861",
        "colourName": "Cocoa - Light",
        "hex": "#987878"
    },
    {
        "dmcNumber": "3862",
        "colourName": "Mocha Beige - Dark",
        "hex": "#583828"
    },
    {
        "dmcNumber": "3863",
        "colourName": "Mocha Beige - Medium",
        "hex": "#A87858"
    },
    {
        "dmcNumber": "3864",
        "colourName": "Mocha Beige - Light",
        "hex": "#987858"
    },
    {
        "dmcNumber": "3865",
        "colourName": "Winter White",
        "hex": "#D8D8C8"
    },
    {
        "dmcNumber": "3866",
        "colourName": "Mocha Brown - Ultra Very Light",
        "hex": "#D8D8C8"
    },
    {
        "dmcNumber": "B5200",
        "colourName": "Snow White",
        "hex": "#D8D8D8"
    },
    {
        "dmcNumber": "Ecru",
        "colourName": "Ecru",
        "hex": "#D8C8A8"
    },
    {
        "dmcNumber": "White",
        "colourName": "White",
        "hex": "#E8E8E8"
    }
] satisfies DmcColour[];
